// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lusovklxvtzhluekhwvu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imx1c292a2x4dnR6aGx1ZWtod3Z1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk5NDIyOTQsImV4cCI6MjA2NTUxODI5NH0.u4cFSTWFbC0ar9Fie1YZW26P-g1a_3iyDHscEWPLZcc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);